blank_issues_enabled: false
contact_links:
  - name: Perguntas e Discussões
    url: https://github.com/ESousa97/Instabytes-Front-End-Imersao-Alura-Google/discussions
    about: Use as discussões para dúvidas gerais e ideias abertas.
